### ISSUE TITLE
Kanban Board - MediMate Appointment Booking App

### ISSUE THREAD

**Issue by mailsg** [mailsg/medimate-backend#10]
Hi,

Below are the team members of the MediMate Appointment Booking App : 
- **Charles Andrews** @forLoop94 
- **Emmanuel Tofa** @uno36 
- **Sandeep Ghosh** @mailsg 

Link to the project kanban board - https://github.com/users/mailsg/projects/7
Link to the back end repo - https://github.com/mailsg/medimate-backend
Link to the front end repo - https://github.com/mailsg/medimate-frontend

![Merged_document](https://github.com/mailsg/medimate-backend/assets/105475440/6636edd0-9106-4d06-a121-2c98f556ee0a)

Kindly review the kanban board and provide feedback.

Thanks

**Comment by Meltrust** [comment]
Hi @mailsg

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] At the time of this review, these are the pointings:

@mails 19
@forLoop94 18
@uno36 10

As you can see, @uno36 has a lot less points than @forLoop94 and @mailsg.  The difference limit is 5 points.

Kindly, make it so no member in the team has more than 5 points difference than any other.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
